---
version: 1
schedule:
  type: simple
  interval: 1s
workflow:
  collect:
    metrics:
      "/intel/psutil/cpu/cpu-total/idle": {}
      "/intel/psutil/cpu/cpu-total/iowait": {}
    publish:
    - plugin_name: slack
      config:
        webhook: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
        publish_fields: "Namespace|Data|Timestamp|Unit"
        channel: "test"